spring:
  datasource:
    username: "root"
    password: "root123"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.64:3306/jt808?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    max-active: 20
    min-idle: 5
    max-wait: 60000
    min-evictable-idle-time-millis: 300000
    max-evictable-idle-time-millis: 300000
    time-between-eviction-runs-millis: 60000
    validation-query: select 1
    validation-query-timeout: -1
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    pool-prepared-statements: true
    filters: stat,wall,log4j
    share-prepared-statements: true

  # rabbitmq config
  rabbitmq:
    business:
      host: 192.168.8.64
      password: root#123
      port: 5672
      username: root
      virtual-host: /
    logs:
      host: 192.168.8.64
      password: root#123
      port: 5672
      username: root
      virtual-host: /

  # mongodb多数据源配置
  mongodb:
    primary:
      uri: mongodb://192.168.8.64:5000/Business
      database: Business
    secondary:
      uri: mongodb://192.168.8.64:5000/Logs
      database: Logs